id: P005506
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:55:23.575448
source_metadata:
  id: bdr:W1KG15849
  title: དཔྱད་རྩོམ་ཕྱོགས་སྒྲིག་ཆོས་རིག་གསལ་བའི་ཉིན་བྱེད།
  author: ''
  volumes:
    55619ee014564713852f5e98e2e1bc4a:
      image_group_id: I1KG15851
      title: ''
      volume_number: 1
      total_pages: 110
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
