id: P005506
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG15849
  title: དཔྱད་རྩོམ་ཕྱོགས་སྒྲིག་ཆོས་རིག་གསལ་བའི་ཉིན་བྱེད།
  author: ''
  volumes:
    55619ee014564713852f5e98e2e1bc4a:
      image_group_id: I1KG15851
      title: ''
      volume_number: 1
      total_pages: 110
      base_file: v001.txt
