id: I49530283
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:23:45+00:00'
last_modified: '2022-06-08T03:34:14.676581+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15849
  title: དཔྱད་རྩོམ་ཕྱོགས་སྒྲིག་ཆོས་རིག་གསལ་བའི་ཉིན་བྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2CC3:
      image_group_id: I1KG15851
      title: ''
      total_pages: 110
      order: 1
      base_file: 2CC3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
